name: context_collector
description: A desktop app for collecting and combining text from multiple files.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  desktop_drop: ^0.6.0
  file_selector: ^1.0.3
  window_manager: ^0.4.3
  flutter_helper_utils: ^8.0.2
  dart_helper_utils: ^5.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  desktop_webview_window: ^0.2.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/editor/
    - assets/monaco/
    - assets/monaco/vs/
    - assets/monaco/vs/editor/
    - assets/monaco/vs/basic-languages/
    - assets/monaco/vs/language/
    # Include monaco-editor directory with all subfolders
    - assets/monaco/monaco-editor/
    - assets/monaco/monaco-editor/min/
    - assets/monaco/monaco-editor/min/vs/
    - assets/monaco/monaco-editor/min/vs/editor/
    - assets/monaco/monaco-editor/min/vs/basic-languages/
    - assets/monaco/monaco-editor/min/vs/language/
    # Add nested subdirectories for each language
    - assets/monaco/monaco-editor/min/vs/basic-languages/dart/
    - assets/monaco/monaco-editor/min/vs/basic-languages/javascript/
    - assets/monaco/monaco-editor/min/vs/basic-languages/typescript/
    - assets/monaco/monaco-editor/min/vs/basic-languages/html/
    - assets/monaco/monaco-editor/min/vs/basic-languages/css/
    - assets/monaco/monaco-editor/min/vs/basic-languages/json/
    - assets/monaco/monaco-editor/min/vs/basic-languages/yaml/
    - assets/monaco/monaco-editor/min/vs/basic-languages/markdown/
    - assets/monaco/monaco-editor/min/vs/basic-languages/python/
    - assets/monaco/monaco-editor/min/vs/basic-languages/shell/
    - assets/monaco/monaco-editor/min/vs/basic-languages/xml/
    - assets/monaco/monaco-editor/min/vs/language/css/
    - assets/monaco/monaco-editor/min/vs/language/html/
    - assets/monaco/monaco-editor/min/vs/language/json/
    - assets/monaco/monaco-editor/min/vs/language/typescript/
    - assets/monaco/themes/

